/* error handling */

/*
    1 - try .. catch 
    2 - on event 
*/

/*
 try { if here is an error it will jump to catch } 
 catch(e){ if an error  } 
 finally{ all sitution will be executed } 
 console.log(" the code after finally will be executed if no error inside the catch ")
*/

